### ISSUE TITLE
How to modify zipfian_const of the zipfian distribution?

### ISSUE THREAD

**Issue by hanke8** [ls4154/YCSB-cpp#11]
Hello,
  Can I modify the _zipfian_const_ of zipfian without any side effect? 
  In addition, to modify zipfian_const, I change “_key_chooser_ = new ScrambledZipfianGenerator(record_count_ + new_keys);_”  to “_key_chooser_ = new ScrambledZipfianGenerator(0, record_count_ + new_keys - 1, zipfian_const);_” in _void CoreWorkload::Init(const utils::Properties &p) { ... }_ 
  Is there any other way, such as modifying this parameter directly in the configuration file?
  Thank you!

**Comment by ls4154** [comment]
I've added configuration for zipfian constant. (2bad0a3)
You can use it by passing `zipfian_const=0.99` option.
